config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  resources :products
  resource :cart, only: [:show] do
    delete :empty, on: :member
  end
  resources :line_items, only: [:create]
  resources :orders
  root 'store#index', as: :store
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items

  def empty!
    line_items.destroy_all
  end

  def add_to_cart(product_id)
    current_item = line_items.where(product_id: product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.sum(&:total_price)
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

  before_validation :set_price, on: :create

  validate :cart_required, on: :create
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1, only_integer: true  }

  def total_price
    price * quantity
  end

  private

  def cart_required
    errors.add(:cart, "cart must existed on create!") unless cart.present?
  end

  def set_price
    self.price = product&.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

  validates :name, :email, :address, :pay_type, presence: true
  validates :pay_type, inclusion: { in: PAYMENT_TYPES }

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      self.line_items << item
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :image_url, presence: true, format: { with: %r{\.(gif|jpg|png)\Z}i, message: "must be a URL for GIF, JPG or PNG image.", allow_blank: true }
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line Items presnet")
      throw :abort
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_cart

  private

  def current_cart
    @current_cart ||= Cart.find session[:cart_id]
  rescue ActiveRecord::RecordNotFound
    @current_cart = Cart.create!
    session[:cart_id] = @current_cart.id

    @current_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  end

  def empty
    current_cart.empty!
    redirect_to store_path, notice: "Your cart has been empty!"
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @line_item = current_cart.add_to_cart(params[:product_id])

    @line_item.save

    respond_to do |format|
      format.html { redirect_to store_url }
      format.js { @current_item = @line_item }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    if current_cart.line_items.empty?
      redirect_to store_url, notice: "Your cart is empty"
      return
    end

    @order = Order.new
  end

  def create
    @order = Order.new(params.require(:order).permit(:name, :address, :email, :pay_type))
    @order.add_line_items_from_cart(current_cart)

    if @order.save
      redirect_to store_path
    else
      render :new
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }

        @products = Product.all
        ActionCable.server.broadcast 'products', html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<h2>Your Pragmatic Cart</h2>
<table>
    <%= render partial: 'line_items/line_item', collection: current_cart.line_items.includes(:product).all %>
  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(current_cart.total_price) %></td>
  </tr>
</table>
<%= button_to "Checkout", new_order_path, method: :get %>
<%= button_to "Empty cart", empty_cart_path, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<%= render partial: 'cart' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body class="<%= controller_name %>">
    <div id="banner">
      <%= image_tag("logo.png") %>
      <span>Store</span>
    </div>
    <div id="columns">
      <div id="side">
        <div id="cart">
          <%= render "carts/cart" %>
        </div>
        <ul>
          <li> <%= link_to "Home", store_url %> </li>
          <li><a href="#">Faq</a></li>
        </ul>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item">
  <% else %>
  <tr>
<% end %>
  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.product.title %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/create.js.erb
$("#cart").html("<%= j render(partial: 'carts/cart') %>")

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/orders/_form.html.erb
<%= form_for order do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>
      <ul>
        <% order.errors.full_messages.each do |message| %> <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= f.label :pay_type %>
    <%= f.select :pay_type, Order::PAYMENT_TYPES, prompt: 
"Select a payment type" %>
  </div>

  <div class="actions">
    <%= f.submit "Place Order" %>
  </div>
<% end %>

app/views/orders/new.html.erb
<div class="depot_form">
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render "form", order: @order %>
  </fieldset>
</div>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 6 %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= image_tag product.image_url, class: 'list_image' %></td>
        <td class="list_description">
          <dl>
            <dt> <%= product.title %> </dt>
            <dd> <%= truncate strip_tags(product.description), length: 80 %> </dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', product %> <br />
          <%= link_to 'Edit', edit_product_path(product) %> <br />
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/_product.html.erb
<% cache(['entry', product]) do %>
<div class="entry">
  <%= image_tag(product.image_url) %>
  <h3><%= product.title %></h3>
  <%= sanitize(product.description) %>
  <div class="price_line">
    <span class="price"><%= number_to_currency(product.price) %></span>
    <%= button_to("Add to Cart", line_items_path(product_id: product.id), remote: true)  %>
  </div>
</div>
<% end %>

app/views/store/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Your Pragmatic Catalog</h1>
<% cache(["store", Product.maximum(:updated_at)]) do %>
  <%= render partial: 'store/product', collection: @products, as: :product %>
<% end %>